server:
  port: 8081
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
      host: 192.168.149.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
