server:
  port: 80


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-order-service
  # zipkin 链路追踪相关配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值，介于0-1之间，1则表示全部采集
      probability: 1