server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848
        # 换成nginx的1111端口
        server-addr: 192.168.149.129:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"
