server:
  port: 80

spring:
  application:
    name: cloud-consumer-feign-hystrix-order80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7001.com:7002/eureka/
feign:
  hystrix:
    enabled: true
